// user_repo.go — Phase 1.A.1 users collection repo.
//
// Schema: `users` Mongo collection keyed by `id` (32-char hex generated by
// the handler). A separate unique index on `email` enforces global
// uniqueness. PasswordHash is stored alongside the user; never returned
// from any HTTP handler because the domain.User json tag scrubs it.
package mongo

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/finance_next/gateway/internal/domain"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
)

// UserCollectionName is the Mongo collection for auth users.
const UserCollectionName = "users"

// Errors returned by UserRepo.
var (
	ErrUserNotFound      = errors.New("user not found")
	ErrUserEmailConflict = errors.New("user with this email already exists")
)

// UserRepo wraps the `users` collection.
type UserRepo struct {
	col *mongo.Collection
}

// NewUserRepo binds the given DB and returns a repository for users.
func NewUserRepo(db *mongo.Database) *UserRepo {
	return &UserRepo{col: db.Collection(UserCollectionName)}
}

// UserIndexModels returns the index models EnsureIndexes installs.
// Exported so unit tests can lock down the partial-admin filter
// without a live Mongo connection.
func UserIndexModels() []mongo.IndexModel {
	return []mongo.IndexModel{
		{
			Keys:    bson.D{{Key: "id", Value: 1}},
			Options: options.Index().SetUnique(true).SetName("uniq_id"),
		},
		{
			Keys: bson.D{{Key: "email", Value: 1}},
			// Case-insensitive collation so "Alice@x.com" and "alice@x.com"
			// collide. We also lowercase emails on write, so this is
			// belt-and-suspenders — index is the hard constraint.
			Options: options.Index().
				SetUnique(true).
				SetName("uniq_email_ci").
				SetCollation(&options.Collation{Locale: "en", Strength: 2}),
		},
		{
			Keys: bson.D{{Key: "role", Value: 1}},
			Options: options.Index().
				SetUnique(true).
				SetName("uniq_admin_role").
				// Partial filter: only docs with role=="admin" participate
				// in the unique constraint. role=="member" rows coexist
				// freely. This makes the bootstrap admin role globally
				// at-most-once across the whole users collection — Fix 5
				// defends against the first-admin race where two
				// concurrent /auth/register calls both see Count()==0.
				SetPartialFilterExpression(bson.M{"role": "admin"}),
		},
	}
}

// EnsureIndexes creates:
//   - unique(id)    — primary id lookup (handler-assigned 32 hex chars)
//   - unique(email) — global email uniqueness, case-insensitive (collation)
//   - partial unique(role="admin") — Fix 5: defends against the
//     first-admin race. Even if two concurrent /auth/register calls
//     both observe Count()==0 and try to insert with role=admin,
//     Mongo rejects the loser with a duplicate-key error and the
//     handler maps it to a 409 conflict.
func (r *UserRepo) EnsureIndexes(ctx context.Context) error {
	_, err := r.col.Indexes().CreateMany(ctx, UserIndexModels())
	return err
}

// Count returns the total number of users. Used at boot to decide
// whether the very next /auth/register grants admin role.
func (r *UserRepo) Count(ctx context.Context) (int64, error) {
	return r.col.CountDocuments(ctx, bson.D{})
}

// CountByRole returns the number of users with the given role. Used by
// the claim-legacy endpoint to refuse the migration unless exactly one
// admin exists — otherwise legacy `userId="default"` rows could be
// silently re-homed to whichever admin made the call first.
func (r *UserRepo) CountByRole(ctx context.Context, role string) (int64, error) {
	return r.col.CountDocuments(ctx, bson.D{{Key: "role", Value: role}})
}

// Insert persists a new user. Returns ErrUserEmailConflict on duplicate
// email (case-insensitive). The caller is expected to set CreatedAt /
// UpdatedAt; Insert does NOT touch them.
func (r *UserRepo) Insert(ctx context.Context, u *domain.User) error {
	if u.Email == "" {
		return errors.New("user email required")
	}
	if u.ID == "" {
		return errors.New("user id required")
	}
	// Normalise email to lowercase so login lookups can match a
	// caller-typed mixed-case address without a second round-trip.
	u.Email = strings.ToLower(u.Email)
	_, err := r.col.InsertOne(ctx, u)
	if err != nil {
		if mongo.IsDuplicateKeyError(err) {
			return ErrUserEmailConflict
		}
		return err
	}
	return nil
}

// FindByID returns the user identified by its handler-generated hex id.
func (r *UserRepo) FindByID(ctx context.Context, id string) (*domain.User, error) {
	var u domain.User
	err := r.col.FindOne(ctx, bson.D{{Key: "id", Value: id}}).Decode(&u)
	if errors.Is(err, mongo.ErrNoDocuments) {
		return nil, ErrUserNotFound
	}
	if err != nil {
		return nil, err
	}
	return &u, nil
}

// FindByEmail returns the user with the given email (case-insensitive).
// Returns ErrUserNotFound when no row matches.
func (r *UserRepo) FindByEmail(ctx context.Context, email string) (*domain.User, error) {
	email = strings.ToLower(strings.TrimSpace(email))
	var u domain.User
	err := r.col.FindOne(ctx,
		bson.D{{Key: "email", Value: email}},
		// Match against the same case-insensitive collation as the index
		// so we don't have to materialise both cases on write.
		options.FindOne().SetCollation(&options.Collation{Locale: "en", Strength: 2}),
	).Decode(&u)
	if errors.Is(err, mongo.ErrNoDocuments) {
		return nil, ErrUserNotFound
	}
	if err != nil {
		return nil, err
	}
	return &u, nil
}

// SetLastLogin stamps a successful login. Best-effort: errors are
// returned but the caller can choose to log-and-ignore — a failed
// timestamp update should not block an otherwise successful login.
func (r *UserRepo) SetLastLogin(ctx context.Context, id string, at time.Time) error {
	res, err := r.col.UpdateOne(ctx,
		bson.D{{Key: "id", Value: id}},
		bson.M{"$set": bson.M{"lastLoginAt": at, "updatedAt": at}},
	)
	if err != nil {
		return err
	}
	if res.MatchedCount == 0 {
		return ErrUserNotFound
	}
	return nil
}
