package crypto

import (
	"encoding/hex"
	"testing"
)

// Golden vector — generated by testdata/gen_vector.mjs (Node's crypto.createCipheriv).
// If this drifts, regenerate with: node testdata/gen_vector.mjs
const (
	goldenKeyHex    = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	goldenIVHex     = "0123456789abcdef01234567"
	goldenPlaintext = "hello-finance_next"
	goldenExpected  = "ASNFZ4mrze8BI0Vn.GuLf1Ldp7+9yvqLGYiHcXQ==.wYY2u5d23W+dKBiGmmDLuN5s"
)

func TestGoldenVector(t *testing.T) {
	svc, err := New(goldenKeyHex)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	iv, err := hex.DecodeString(goldenIVHex)
	if err != nil {
		t.Fatalf("hex decode iv: %v", err)
	}
	got, err := svc.encryptWithIV(iv, goldenPlaintext)
	if err != nil {
		t.Fatalf("encryptWithIV: %v", err)
	}
	if got != goldenExpected {
		t.Fatalf("ciphertext mismatch\n  got:  %s\n  want: %s", got, goldenExpected)
	}
}

func TestDecryptByteCompatibleWithNode(t *testing.T) {
	svc, err := New(goldenKeyHex)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	pt, err := svc.Decrypt(goldenExpected)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if pt != goldenPlaintext {
		t.Fatalf("plaintext mismatch\n  got:  %q\n  want: %q", pt, goldenPlaintext)
	}
}

func TestEncryptDecryptRoundTrip(t *testing.T) {
	svc, err := New(goldenKeyHex)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	plain := "some-secret-api-key-with-symbols!@#$%^&*()"
	ct, err := svc.Encrypt(plain)
	if err != nil {
		t.Fatalf("Encrypt: %v", err)
	}
	pt, err := svc.Decrypt(ct)
	if err != nil {
		t.Fatalf("Decrypt: %v", err)
	}
	if pt != plain {
		t.Fatalf("round trip mismatch: got %q want %q", pt, plain)
	}
}

func TestNewRejectsBadKey(t *testing.T) {
	if _, err := New("tooShort"); err == nil {
		t.Fatal("expected error for short key")
	}
	if _, err := New("zz" + goldenKeyHex[2:]); err == nil {
		t.Fatal("expected error for non-hex key")
	}
}

func TestDecryptRejectsMalformed(t *testing.T) {
	svc, err := New(goldenKeyHex)
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	cases := []string{
		"",
		"only-one-part",
		"a.b",
		"!!.!!.!!",
	}
	for _, c := range cases {
		if _, err := svc.Decrypt(c); err == nil {
			t.Fatalf("expected error for %q", c)
		}
	}
}
